<a href="https://colab.research.google.com/github/rfps09/Colab-Backup/blob/main/PerceptronSimples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Perceptron de camada simples para classificar maça e laranja por peso e ph

OBS: Apenas trocando a ordem de entrada na rede neural, de maneira com que entre toda os inputs de uma classe antes de entrar os inputs de outra. O número de épocas necessárias para o aprendizado cai em 24.505, aproximadamente 39%.

In [ ]:
import numpy as np

q=6
numEpocas = 39220

Peso = np.array([113,107,98,115,122,120])
pH = np.array([6.8, 5.2, 3.6, 2.9, 4.7, 4.2])

X = np.vstack((Peso,pH))
Y = np.array([-1,-1,-1,1,1,1])

bias = 1

eta = 0.1

W = np.zeros(3)

e = np.zeros(q)

def funcaoDeAtivicao(valor):
    if valor < 0.0:
        return -1
    return 1

for i in range(numEpocas):
    for j in range(q):
        Xb = np.hstack((bias,X[:,j]))
        
        V = np.dot(W, Xb)
        
        Yr = funcaoDeAtivicao(V)
        
        e[j] = Y[j] - Yr
        
        W = W + eta*e[j]*Xb
    
print("Vetor de erros (e) = " + str(e))

Vetor de erros (e) = [0. 0. 0. 0. 0. 0.]


Perceptron de camada simples para reproduzir a porta lógica NOT

In [ ]:
import numpy as np

numEpocas = 6
q = 3

X = np.array([0,1,-1])
Y = np.array([1,0,0])
W = np.zeros(2)
e = np.zeros(3)
bias = 1
eta = 0.1

def funcaoDeAtivicao(valor):
    if valor < 0.0:
        return 0
    return 1

for j in range(numEpocas):
  for i in range(q):
    Xb = np.hstack((bias,X[i]))
    V = np.dot(W,Xb)
    Yr = funcaoDeAtivicao(V)
    e[i] = Y[i] - Yr
    W = W + eta*e[i]*Xb
  
print("O vetor de pesos (W) + Bias = " + str(W[1]) + "x + " + str(bias*W[0]))
print("O vetor de erros (e) = " + str(e))

O vetor de pesos (W) + Bias = 0.0x + -0.1
O vetor de erros (e) = [1. 0. 0.]


Perceptron de camada simples para reproduzir a porta lógica OR

In [ ]:
import numpy as np

numEpocas = 4
q = 4

X1 = np.array([0,0,1,1])
X2 = np.array([0,1,0,1])
X = np.vstack((X1,X2))
Y = np.array([0,1,1,1])
W = np.zeros(3)
e = np.zeros(q)
bias = 1
eta = 0.1

def funcaoDeAtivicao(valor):
    if valor < 0.0:
        return 0
    return 1

for j in range(numEpocas):
    for i in range(q):
        Xb = np.hstack((bias, X[:,i]))
        V = np.dot(W,Xb)
        Yr = funcaoDeAtivicao(V)
        e[i] = Y[i] - Yr
        W = W + eta*e[i]*Xb
        print(W)

print("O vetor de erros (e) = " + str(e))


[-0.1  0.   0. ]
[0.  0.  0.1]
[0.  0.  0.1]
[0.  0.  0.1]
[-0.1  0.   0.1]
[-0.1  0.   0.1]
[0.  0.1 0.1]
[0.  0.1 0.1]
[-0.1  0.1  0.1]
[-0.1  0.1  0.1]
[-0.1  0.1  0.1]
[-0.1  0.1  0.1]
[-0.1  0.1  0.1]
[-0.1  0.1  0.1]
[-0.1  0.1  0.1]
[-0.1  0.1  0.1]
O vetor de erros (e) = [0. 0. 0. 0.]


Perceptron de camada simples para reproduzir a porta lógica AND

In [ ]:
import numpy as np

numEpocas = 6
q = 4

X1 = np.array([0,0,1,1])
X2 = np.array([0,1,0,1])
X = np.vstack((X1,X2))
Y = np.array([0,0,0,1])
W = np.zeros(3)
bias = 1
eta = 0.1
e = np.zeros(q)

for j in range(numEpocas):
    for i in range(q):
        Xb = np.hstack((bias, X[:,i]))
        V = np.dot(W, Xb)
        Yr = np.heaviside(V,0)
        e[i] = Y[i]-Yr
        W = W + eta*e[i]*Xb
        
print("O vetor de erros (e) = " + str(e))
print(str(W))

O vetor de erros (e) = [0. 0. 0. 0.]
[-0.2  0.2  0.1]


Perceptron de camada simples para classificar duas classes com distribuição gaussiana. Valores médios μ1 = -10, μ2 = 10 e variancias iguais e unitárias σ = 1

In [ ]:
import numpy as np

def unison_shuffled_copies(a, b):
    assert len(a) == len(b)
    p = np.random.permutation(len(a))
    return a[p], b[p]

numEpocas = 2
q = 50

X1 = np.random.normal(10,1,q)
X2 = np.random.normal(-10,1,q)
X = np.hstack((X1,X2))
Y = np.array([1,-1])
Y = np.repeat(Y,q)

X,Y = unison_shuffled_copies(X,Y)

print(str(X))

W = np.zeros(2)
e = np.ones(q*2)
bias = 1
eta = 0.1

for j in range(numEpocas):
  for i in range(q*2):
    Xb = np.hstack((bias,X[i]))
    V = np.dot(W,Xb)
    Yr = np.sign(V)
    e[i] = Y[i] - Yr
    W = W + eta*e[i]*Xb

print("O vetor de erros (e) = " + str(e))

[  9.21406812  10.80146101  -8.34471714  10.14747848  11.18710504
 -12.35153113  -9.25683184 -10.48167619 -11.43933734  10.43624258
   9.26819676  11.73447816  -9.12932838 -11.24652239 -10.81117142
   9.68603058 -10.45920735  -8.47369471  10.50907303   9.71980701
 -10.4741603    8.28388261  11.1288355   11.66486484   8.31679382
 -12.32368934  -9.49768785 -10.35851576  10.54113854 -10.29388511
  -9.96900053  -9.4662577   10.13171636 -11.57051684  10.77169599
  10.37166157 -10.75967885  -9.32318102  10.58189281  -9.8564549
   8.46435699 -10.28053841  -8.89064824  12.22579723  -8.99851042
  -9.60388523  11.45340678  10.25405041   9.39349948 -10.10496122
 -11.07000772 -10.25039333   8.96208373  11.01390683   8.24498418
 -10.96893379   8.48371749   9.4451784    9.87004393  10.42758492
   9.84451074   9.99070754   9.81619246   9.97006312  11.57211701
 -11.66395387  -8.99049995  11.27768488 -10.17960973  11.04819917
   8.14405757  -8.8711544   -9.86767303   7.8290924  -10.69973325
  11.113905

Tentativa de usar rede perceptron de um neurônio para aprender a porta lógica XOR

In [ ]:
import numpy as np

numEpocas = 10000
q = 4

X1 = np.array([0,0,1,1])
X2 = np.array([0,1,0,1])
X = np.vstack((X1,X2))
Y = np.array([0,1,1,0])
W = np.zeros(3)
e = np.zeros(q)
bias = 1
eta = 0.1

def funcaoDeAtivacao(value):
  if(value < 0.0):
    return 0
  return value

for j in range(numEpocas):
  for i in range(q):
    Xb = np.hstack((bias,X[:,i]))
    V = np.dot(W,Xb)
    Yr = np.heaviside(V,0)
    e[i] = Y[i] - Yr
    W = W + eta*e[i]*Xb

print(str(e))

[-1.  1.  1. -1.]


-matriz de confusao

-acuracia

-f1 score

-precisao

-recall